### ISSUE TITLE
exec user process caused "permission denied"

### ISSUE THREAD

**Issue by EVOTk** [qdm12/youtube-dl-docker#1]
Hello,

I can not seem to execute the container, despite having followed the recommendations permissions.

My Compose : 

```
version: "3.7"
services:
  youtube-dl:
    image: qmcgaw/youtube-dl-alpine
    container_name: youtube-dl
    network_mode: bridge
    user: "1030:100"
    environment:
      - LOG=yes
      - AUTOUPDATE=yes
    volumes:
      - /volume1/Download/youtubedl:/downloads
    command: |
      https://www.youtube.com/watch?v=HagVnWAeGcM
      -o "/downloads/%(title)s-%(duration)s.%(ext)s"
```
![2021-02-09 19_24_38-Window](https://user-images.githubusercontent.com/45015615/107409576-9c3daf80-6b0c-11eb-868f-647618807501.png)

![fO5rlAH](https://user-images.githubusercontent.com/45015615/107409594-a1026380-6b0c-11eb-8432-42387d7ccca4.png)

My "docker" user is the owner of the folder, and does have the PUID / GUID 1030/100.

My error : `standard_init_linux.go:222: exec user process caused "permission denied"`

Thx
